services:
  keycloak_postgres:
    container_name: keycloak_postgres
    image: postgres:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-keycloak}
      POSTGRES_USER: ${POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    ports:
      - 5432
    volumes:
      - ./data/:/var/lib/postgresql/data
    networks:
      - siberiana-network

  keycloak_service:
    container_name: keycloak_service
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    environment:
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
      KC_DB_USERNAME: ${KC_DB_USERNAME:-keycloak}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-changeme}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-master}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-changeme}
    ports:
      - 8080
    networks:
      - siberiana-network
    depends_on:
      - keycloak_postgres

volumes:
  data:

networks:
  siberiana-network:
    external: true
