services:
  siberiana_keycloak_postgres:
    container_name: siberiana_keycloak_postgres
    image: postgres:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 15432:5432
    volumes:
      - siberiana_keycloak_data:/var/lib/postgresql/data
    networks:
      - siberiana-network

  siberiana_keycloak_service:
    container_name: siberiana_keycloak_service
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    environment:
      KC_DB_URL: jdbc:postgresql://siberiana_keycloak_postgres:5432/keycloak
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - 10001:8080
    networks:
      - siberiana-network
    depends_on:
      - siberiana_keycloak_postgres

volumes:
  siberiana_keycloak_data:
    external: true

networks:
  siberiana-network:
    external: true
